# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x04test\"\x8e\x01\n\x04\x44\x61ta\x12\x0b\n\x03str\x18\x01 \x01(\t\x12\x0b\n\x03int\x18\x02 \x01(\x03\x12\r\n\x05\x66loat\x18\x03 \x01(\x01\x12\"\n\x04\x64ict\x18\x04 \x03(\x0b\x32\x14.test.Data.DictEntry\x12\x0c\n\x04list\x18\x05 \x03(\t\x1a+\n\tDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\".\n\x04Test\x12\x1d\n\x04root\x18\x01 \x01(\x0b\x32\n.test.DataH\x00\x88\x01\x01\x42\x07\n\x05_rootb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATA_DICTENTRY._options = None
  _DATA_DICTENTRY._serialized_options = b'8\001'
  _globals['_DATA']._serialized_start=21
  _globals['_DATA']._serialized_end=163
  _globals['_DATA_DICTENTRY']._serialized_start=120
  _globals['_DATA_DICTENTRY']._serialized_end=163
  _globals['_TEST']._serialized_start=165
  _globals['_TEST']._serialized_end=211
# @@protoc_insertion_point(module_scope)
